### ISSUE TITLE
REAL() can only be applied to a 'numeric', not a 'integer'

### ISSUE THREAD

**Issue by NguyenThanhTan** [saraswatmks/Machine-Learning-in-R#3]
As title, when I encourtered this error when I ran to the line:
`mytune <- tuneParams(learner = lrn, task = traintask, resampling = rdesc, measures = acc, par.set = params, control = ctrl, show.info = T)`
Then I changed `makeIntegerParam("max_depth",lower = 3L,upper = 10L)` to `makeNumericParam("max_depth",lower = 3L,upper = 10L)`, the error gone. But after that I couldn't run this line `lrn_tune <- setHyperPars(lrn,par.vals = mytune$x)` because of another error `Error in setHyperPars2.Learner(learner, insert(par.vals, args)) : 
  5.065 is not feasible for parameter 'max_depth'!`
I know that max_depth must be integer but can't help. Did I miss something?

**Comment by saraswatmks** [comment]
Hi @NguyenThanhTan max_depth of a tree can't be in decimal. Check your params. Is it 5.065 ? Also, which script is it?

**Comment by NguyenThanhTan** [comment]
Tks for your reply, I fixed it 👍
